# Add Elements to a NumPy Array

In [1]:
import numpy as np

In [3]:
nums = np.arange(5)

nums

array([0, 1, 2, 3, 4])

## Add Item to Array

In [4]:
new_nums = np.append(nums, 5)

print(nums)
print(new_nums)

[0 1 2 3 4]
[0 1 2 3 4 5]


In [5]:
new_nums = np.concatenate([ nums, [5], [6,7,8], [9,10]])

print(new_nums)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [7]:
new_nums = np.insert(nums, 2, 9)

print(nums)
print(new_nums)

[0 1 2 3 4]
[0 1 9 2 3 4]
