# NumPy Element Selection

In [1]:
import numpy as np

In [2]:
nums = np.arange(10)
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
gt4 = nums > 4

print(gt4)

# nums_gt4 = nums[gt4]
# print(nums_gt4)

print(nums[ [True, False, True, True, False, False, False, True, False, True ] ])

[False False False False False  True  True  True  True  True]
[0 2 3 7 9]


In [8]:
nums[nums > 4] * -1

array([-5, -6, -7, -8, -9])

In [9]:
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
new_nums = nums[nums > 4] * -1

In [11]:
print(nums)
print(new_nums)

[0 1 2 3 4 5 6 7 8 9]
[-5 -6 -7 -8 -9]


In [12]:
nums

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nums[1] = 9

print(nums)

[0 9 2 3 4 5 6 7 8 9]


In [16]:
nums[ [1, 3] ] = 9

print(nums)

[0 9 2 9 4 5 6 7 8 9]


In [23]:
nums = np.arange(10)

gt4 = nums > 4
print(gt4)

new_nums = nums[gt4] * -1

nums[gt4] = new_nums

# less efficient to calculate the selection of greater than 4 twice
# nums[nums > 4] = nums[nums > 4] * -1

print(nums)

[False False False False False  True  True  True  True  True]
[ 0  1  2  3  4 -5 -6 -7 -8 -9]


In [18]:
nums = np.arange(10)

nums[ [1, 3] ] = nums[ [1, 3] ] * -1

print(nums)

[ 0 -1  2 -3  4  5  6  7  8  9]


In [24]:
matrix_nums = np.arange(36).reshape(6,6)

print(matrix_nums)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [25]:
onedim_nums = matrix_nums.reshape(36)

onedim_nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [26]:
onedim_nums[18] = 9999

onedim_nums

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17, 9999,   19,   20,   21,
         22,   23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
         33,   34,   35])

In [27]:
matrix_nums

array([[   0,    1,    2,    3,    4,    5],
       [   6,    7,    8,    9,   10,   11],
       [  12,   13,   14,   15,   16,   17],
       [9999,   19,   20,   21,   22,   23],
       [  24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35]])

In [28]:
matrix_nums[1, 3]

9

In [29]:
matrix_nums[1, :]

array([ 6,  7,  8,  9, 10, 11])

In [30]:
matrix_nums[:, 1]

array([ 1,  7, 13, 19, 25, 31])

In [31]:
matrix_nums[1, 1:5:2]

array([7, 9])