# NumPy Array Ops

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3], dtype=np.int16)

arr2 = np.array([4,5,6], dtype=np.int16)

arr3 = np.array([7,8], dtype=np.int16)

In [5]:
print(arr1.shape)
print(arr2.shape)

arr1 + arr2

(3,)
(3,)


array([5, 7, 9], dtype=int16)

In [6]:
print(arr1.shape)
print(arr3.shape)

arr1 + arr3

(3,)
(2,)


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [7]:
arr4 = arr3[:, np.newaxis]

arr4

array([[7],
       [8]], dtype=int16)

In [8]:
print(arr1.shape)
print(arr4.shape)

(3,)
(2, 1)


In [10]:
print(arr1)
print(arr4)

arr1 + arr4

[1 2 3]
[[7]
 [8]]


array([[ 8,  9, 10],
       [ 9, 10, 11]], dtype=int16)

In [17]:
np.array([1,2,3]) + np.array([[4],[5]])

array([[5, 6, 7],
       [6, 7, 8]])

In [18]:
np.dot( [5], [6])

30

In [19]:
np.dot( [5,7], [6,8])

86

In [21]:
np.dot([5,7], [[6],[8]])

array([86])

In [22]:
arr1 = np.array([[3,1],[2,2]], dtype=np.int16)
arr2 = np.array([[4,1,4],[2,2,5]], dtype=np.int16)

print(arr1)
print(arr2)

[[3 1]
 [2 2]]
[[4 1 4]
 [2 2 5]]


In [23]:
np.dot(arr1, arr2)

array([[14,  5, 17],
       [12,  6, 18]], dtype=int16)

In [24]:
np.dot(arr2, arr1)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)